### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by Kesmek** [salihgun/react-native-video-processor#1]
Hello,

This is more of a question than an issue. I'm not an expert on licensing and legal issues but since this library uses the `full-gpl-lts` version of `ffmpeg-kit`, doesn't that mean the the license for this library needs to be GPL as well to conform to the terms of GPL? Here's what I'm referring to for context: https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

**Comment by salihgun** [comment]
Hello,

Thank you for the information. GPL license added.
