### ISSUE TITLE
Video Trimmer Component

### ISSUE THREAD

**Issue by margretheluth** [salihgun/react-native-video-processor#3]
Hey, does anyone know if there will be a trimmer component added? I am struggling to make one with the frames and multi slider.
Thanks! ☺️

**Comment by salihgun** [comment]
Hello, 

I've done it before. I will add it soon as a component. You can star it to be notified.

**Comment by salihgun** [comment]
@margretheluth You can check the latest version.

**Comment by Aycom366** [comment]
@salihgun Thanks for the package. However, I don't know how to download the trimmed video.
can you show me how, please?

**Comment by salihgun** [comment]
You can use a file manager library to download the video, you have the path. @Aycom366

**Comment by Aycom366** [comment]
> You can use a file manager library to download the video, you have the path. @Aycom366 

I'm using the trimmer component to trim and there's no how I can get path after trimming. Because I'm not using any of the video function.
